### ISSUE TITLE
现在mhgui会自动跳转manhuagui了，url会出问题吗

### ISSUE THREAD

**Issue by shinonomeow** [Serge45/mhgui-downloader#1]
两个网站的url是一样的吗

**Comment by shinonomeow** [comment]
唉，过不去，浏览器是正常的，但是requests返回的是403

**Comment by Serge45** [comment]
有 url 讓我試試嗎?我剛才隨意找了一頁，使用 mhgui 跟 manhuagui 都可以，在想可能是目前的解析邏輯有漏洞。

**Comment by shinonomeow** [comment]
> 有 url 讓我試試嗎?我剛才隨意找了一頁，使用 mhgui 跟 manhuagui 都可以，在想可能是目前的解析邏輯有漏洞。

感觉可能是服务器问题，requests的请求一直被ban，我再研究研究

**Comment by shinonomeow** [comment]
> 有 url 讓我試試嗎?我剛才隨意找了一頁，使用 mhgui 跟 manhuagui 都可以，在想可能是目前的解析邏輯有漏洞。

ban日本ip好像，换了个能请求通了，我再试试- -

**Comment by shinonomeow** [comment]
> 有 url 讓我試試嗎?我剛才隨意找了一頁，使用 mhgui 跟 manhuagui 都可以，在想可能是目前的解析邏輯有漏洞。

感谢，很好用的漫画下载！！！
